### PR TITLE
Support for zend-hydrator v3

### PR DESCRIPTION
**Pull request by michalbundyra**
Alternative to #1

### CODE REVIEW

**Comment by michalbundyra** [comment]
@TomHAnderson please review

**Comment by TomHAnderson** [comment]
I'm satisfied with this PR and if you're ready too I'll merge it and release as 2.0.0

**Review by TomHAnderson — APPROVED** [review]

**Comment by michalbundyra** [comment]
@TomHAnderson Thanks for the review.
Before we release I would like apply some other features and changes, as we are bumping to new major. I would like to add typehints and RTH everywhere, and apply some other PHP 7.2 features, so we can stay on 2.x a bit longer ;-) What do you think?

**Comment by TomHAnderson** [comment]
I'll leave the PR as-is until you push the additional changes

**Pull request merged**
