### PR TITLE
Added zend-hydrator v3 support [No BC Break]

### PR DESCRIPTION
**Pull request by michalbundyra**

### CODE REVIEW

**Comment by michalbundyra** [comment]
@TomHAnderson What do you think? I have to say that I do not like this solution too much, and it's quite messy, but ... by doing it this way we can keep backward compatibility and release it with 1.1.0.

**Comment by TomHAnderson** [comment]
I haven't seen this method of aliasing classes and having duplicate class structures before.  It is messy and doesn't provide for a cleaner future.  A hydrator v4 would duplicate the structure again.

This library is just-now being moved to the doctrine namespace and github account.  The new packagist for this is https://packagist.org/packages/doctrine/doctrine-zend-hydrator with only a 1.0 release.

My preference when moving between major versions is to version my own library with a new major version.  For instance https://packagist.org/packages/api-skeletons/zf-oauth2-doctrine has a 1.x, 2.x, and 3.x depending on php version.  Though php versioning is an extreme major version change it is still a valid example of why major version changes to support major requirements changes are applicable.

I think in theory this method is valid but I don't see a benefit to it in this case.  For this library's limited distribution (12 installs) I would much rather see two active branches 1.x for Zend Hydrator 2 and 3.x for Zend Hydrator 3, skipping the 2.x version completely for esthetics.

**Comment by michalbundyra** [comment]
@TomHAnderson merged? Why?? I wanted to reject it and create the other PR with zend-hydrator v3 support only... for next major release.

**Comment by TomHAnderson** [comment]
I merged it because without feedback from you I was worried you'd lost
interest.

I'm waiting on this project to be done too for my Symfony port of
zf-doctrine-graphql and I thought merging this and going with it as-is
would help move things along.

Admittedly I was making assumptions.  Without others input the right move
can be tough.

But I specifically didn't create a release.  I really appreciate you
contacting me so quickly about this.  If you agree I'll back out the merge.

**Pull request merged**
